% Recording performance measure 

record_folder = sprintf(exp_folder+"/Record");
model_folder = sprintf(exp_folder+"/Model");
if ~exist(record_folder,'dir')
    mkdir(record_folder)
end
if ~exist(model_folder,'dir')
    mkdir(model_folder)
end

record_path=sprintf("%s/%s_results.csv",record_folder,modelMethod);
if to_syn
    to_syn_const=1;
else
    to_syn_const=0;
end
if ~exist(record_path,'file')
    header = strcat('Trial',sep,'Network Size',sep,'sigma',sep,'T', ...
        sep,'Accuracy',sep,'Precision', ...
        sep,'Recall',sep,'F1score',sep,'to_syn',sep,'lr',...
        sep,'test_Acc',sep,'test_Pre',sep,'test_Rec',sep,'test_F1',sep,'trainingTime',...
        sep,'testingTime',sep,'Number of Center');
    data = strcat(num2str(counter),sep,num2str(config.layers),sep,num2str(sigma), ...
        sep,num2str(T),sep, ...
        num2str(accuracy),sep,num2str(precision),sep,num2str(recall),sep, ...
        num2str(F1score),sep,num2str(to_syn_const),sep,num2str(lr),...
        sep,num2str(test_accuracy),sep,num2str(test_precision),sep,...
        num2str(test_recall),sep,num2str(test_F1score),sep,num2str(trainingTime),...
        sep,num2str(testingTime),sep,num2str(network.numC));

    fid = fopen(record_path, 'w');
    fprintf(fid, '%s\n', header);
    fprintf(fid, '%s\n', data);
    fclose(fid);
else
    data = strcat(num2str(counter),sep,num2str(config.layers),sep,num2str(sigma), ...
        sep,num2str(T),sep, ...
        num2str(accuracy),sep,num2str(precision),sep,num2str(recall),sep, ...
        num2str(F1score),sep,num2str(to_syn_const),sep,num2str(lr),...
        sep,num2str(test_accuracy),sep,num2str(test_precision),sep,...
        num2str(test_recall),sep,num2str(test_F1score),sep,num2str(trainingTime),...
        sep,num2str(testingTime),sep,num2str(network.numC));
    fid = fopen(record_path, 'a');
    fprintf(fid, '%s\n', data);
    fclose(fid);
end

