% Record summary

summary_path=exp_folder+"/summary.csv";
if ~exist(summary_path,'file')
    summary_header= strcat('Model',sep,'NumOfCenter',sep,'Sigma',sep,'Layers',...
                            'T',sep,'Syn_Samp',...
                            sep,'Accuracy',sep,'Precision', ...
                            sep,'Recall',sep,'F1score',sep,'to_syn',sep,'output_syn_num',sep,'lr',...
                            sep,'test_Acc',sep,'test_Pre',sep,'test_Rec',sep,'test_F1');
    fid = fopen(summary_path, 'w');
    fprintf(fid,'%s\n',summary_header);
    fclose(fid);
end
if to_syn == false
    syn_num=0;
end
fid=fopen(summary_path,'a');
summary_data=strcat(modelMethod,sep,num2str(network.numC)...
        ,sep,num2str(ConfSig),sep...
        ,num2str(config.layers),sep,num2str(T),sep,num2str(syn_num),sep,num2str(Acc),sep,num2str(Pr), ...
        sep,num2str(Re),sep,num2str(F1),sep,num2str(to_syn_const),sep,num2str(output_syn_samples),...
        sep,num2str(lr),...
        sep,num2str(test_accuracy),sep,num2str(test_precision),sep,...
        num2str(test_recall),sep,num2str(test_F1score));
fprintf(fid,'%s\n',summary_data);
fclose(fid);
